name: 🚀 Run

on:
  pull_request:
    types: [opened, reopened]
  jobs:
    specific_review_requested:
      runs-on: ubuntu-latest
      if: ${{ github.event.requested_team.name == 'octo-team'}}
      steps:
        - run: echo 'A review from octo-team was requested'

uses: actions/upload-artifcat@v3
id: artifact-upload-step
with:
  name: main.py
  path: main.py
  if-no-files-found: error
  retention-days: 1
  compression-level: 9
  overwrite: true

jobs:
  run:
    name: 🚀 Run
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🚀 Run
        shell: bash
        run: |
          python3 main.py
